services:
  mysql:
    image: mysql:8.0
    #container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: binionsdb
      MYSQL_USER: ohgiraffers
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql


volumes:
  mysql-data:
