version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: binionsdb
      MYSQL_USER: ohgiraffers
      MYSQL_PASSWORD: ohgiraffers
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: test_redis
    ports:
      - "6378:6379"

  app:
    build: .
    ports:
      - "8082:8081"
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
