## server port config
server:
    port: 8081
    error:
        path: /error


## driver config

spring:
    session:
        store-type: redis
    data:
        redis:
            host: redis
            port: 6379
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/beanionsdb
        username: ohgiraffers
        password: ohgiraffers
    mail:
        host: smtp.gmail.com
        port: 587
        username: lmcwul@gmail.com
        password: jouxsxznvyxykceu
        properties:
            mail:
                smtp:
                    ssl:
                        trust: "smtp.gmail.com"
                    auth: true
                    startt  ls:
                        enable: true
    web:
        resources:
            static-locations: classpath:/assets/, file:C:\Lecture\Team-Beanions\src\main\resources\assets\images\upload\user\verify
    file:
        upload:
            path: src/main/resources/assets/images/upload

servlet:
    multipart:
    location: C:\Lecture\Team-Beanions
    max-file-size: 10MB
    max-request-size: 10MB

## mybatis config
mybatis:
    mapper-locations: mapper/**/*.xml